export const UserConfig = {
  about: '',
  agree_search: 0,
  animals: '',
  area_of: '0.00',
  area_to: '100000.00',
  balcony: '',
  bunker: '',
  checked: 0,
  city: '',
  country: '',
  date: undefined,
  day_counts: undefined,
  days: 0,
  distance_green: 0,
  distance_metro: 0,
  distance_parking: 0,
  distance_shop: 0,
  distance_stop: 0,
  dob: undefined,
  facebook: '',
  family: 1,
  firstName: '',
  flat: undefined, // Може бути undefined
  house: undefined, // Може бути undefined
  img: '',
  instagram: '',
  lastName: '',
  looking_man: undefined,
  looking_woman: undefined,
  mail: undefined,
  man: 1,
  metro: '',
  mounths: undefined,
  option_pay: 0,
  price_of: 0,
  price_to: 0,
  purpose_rent: '',
  realll: 0,
  region: '',
  repair_status: 0,
  room: undefined, // Може бути undefined
  rooms_of: 0,
  rooms_to: 0,
  students: 1,
  surName: '',
  telegram: '',
  tell: undefined,
  user_id: '',
  viber: '',
  weeks: undefined,
  woman: 1,
  years: undefined,
  street: '',
  district: '',
  micro_district: '',
  metrocolor: '',
  floor: 0,
  metroname: '',
  filterData: '',
  option_flat: '',

};


export const UsereSearchConfig = {
  about: '',
  agree_search: 0,
  animals: '',
  area_of: '0.00',
  area_to: '100000.00',
  balcony: '',
  bunker: '',
  checked: 0,
  city: '',
  country: '',
  date: undefined,
  day_counts: '',
  distance_green: 0,
  distance_metro: 0,
  distance_parking: 0,
  distance_shop: 0,
  distance_stop: 0,
  dob: undefined,
  facebook: '',
  family: undefined,
  firstName: undefined,
  flat: undefined,
  house: undefined,
  img: undefined,
  instagram: '',
  lastName: undefined,
  looking_man: false,
  looking_woman: false,
  mail: '',
  man: undefined,
  metro: '',
  option_pay: undefined,
  price_of: 0,
  price_to: 0,
  purpose_rent: '',
  realll: 0,
  repair_status: 0,
  room: undefined,
  rooms_of: 0,
  rooms_to: 0,
  students: undefined,
  surName: '',
  telegram: '',
  tell: undefined,
  user_id: '',
  viber: '',
  woman: undefined,

  days: 0,
  weeks: 0,
  mounths: 0,
  years: 0,

  region: '',
  street: '',
  district: '',
  micro_district: '',

  area: 0,
  kitchen_area: 0,
  limit: 0,
  months: undefined,
  price: 0,
  rooms: undefined,
  floor: 0,

  metrocolor: '',
  metroname: '',
  filterData: '',
  option_flat: '',

}

export const HouseConfig = {
  about: '',
  agent_id: undefined,
  animals: '',
  apartment: '',
  area: '',
  balcony: '',
  bunker: '',
  city: '',
  country: 'Україна',
  district: '',
  distance_green: 0,
  distance_metro: 0,
  distance_parking: 0,
  distance_shop: 0,
  distance_stop: 0,
  family: '',
  flat_id: '',
  flat_index: '',
  floor: '',
  houseNumber: '',
  id: 0,
  img: '',
  kitchen_area: 0,
  limit: '',
  man: '',
  metro: '',
  micro_district: '',
  name: '',
  option_flat: 2,
  option_pay: 0,
  owner_id: undefined,
  photos: [],
  price_d: '',
  price_f: '',
  price_m: '',
  price_s: '',
  price_y: '',
  private: 0,
  region: '',
  repair_status: 0,
  rent: 0,
  room: undefined,
  rooms: '',
  selectedKitchen_area: '',
  street: '',
  students: '',
  woman: '',
  metrocolor: '',
  metroname: '',

}

export const StatusConfig = {
  agree_search: 0,
  checked: 0,
  date: undefined,
  family: 1,
  flat: undefined,
  house: undefined,
  looking_man: undefined,
  looking_woman: undefined,
  man: 1,
  realll: 0,
  room: undefined,
  students: 1,
  woman: 1,
};

export const HouseSearchConfig = {
  price_of: undefined,
  price_to: undefined,
  region: undefined,
  city: undefined,
  rooms_of: undefined,
  rooms_to: undefined,
  area_of: '0.00',
  area_to: '100000.00',
  repair_status: 0,
  bunker: undefined,
  balcony: undefined,
  animals: undefined,
  distance_metro: 0,
  distance_stop: 0,
  distance_green: 0,
  distance_shop: 0,
  distance_parking: 0,
  option_pay: undefined,
  purpose_rent: undefined,
  looking_woman: undefined,
  looking_man: undefined,
  students: undefined,
  woman: undefined,
  man: undefined,
  family: undefined,
  days: undefined,
  weeks: undefined,
  months: undefined,
  years: undefined,
  day_counts: undefined,
  room: undefined,
  house: undefined,
  flat: undefined,
  limit: undefined,
  option_flat: undefined,
  country: undefined,
  kitchen_area: 0,
  filterData: undefined,

  about: undefined,
  checked: undefined,
  date: undefined,
  metro: undefined,
  mounths: undefined,

  street: undefined,
  district: undefined,
  micro_district: undefined,
  rooms: undefined,
  private: undefined,
  rent: undefined,
  metrocolor: undefined,
  metroname: undefined,

};
